[package]
name = "qfile"
version = "2.2.1"
edition = "2021"
description = "Crate for accessing a file by path, case insensitive. Automatic detection, create a path with a new file or open an existing file"
repository="https://github.com/m62624/qfile"
categories = ["filesystem"]
keywords = ["file", "auto-path", "case-insensitive"]

license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
lazy_static = "1.4.0"
[dev-dependencies]
rand="0.8.5"
[lib]
doctest = false
