[package]
name = "qfile"
version = "3.0.0"
edition = "2021"
description = "Crate for accessing a file by path, case insensitive. Automatic detection, create a path with a new file or open an existing file"
repository="https://github.com/m62624/qfile"
categories = ["filesystem"]
keywords = ["file","async-io","auto-path", "case-insensitive"]
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
regex = "1.7.0"
lazy_static = "1.4.0"
thiserror = "1.0.38"
threadpool = "1.8.1"
num_cpus = "1.15.0"
async-trait = "0.1.62"
async-recursion = "1.0.2"
walkdir = "2.3.2"
futures = "0.3.26"
async-fs = "1.6.0"
[dev-dependencies]
rand="0.8.5"
[lib]
doctest = false
