name: Rust

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-tests:
      runs-on: ubuntu-latest
      container:
        image: xd009642/tarpaulin:develop-nightly
        options: --security-opt seccomp=unconfined
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin \
          --engine llvm \
          --out xml \
          --output-dir .coverage
      - uses: codecov/codecov-action@v3
        with:
          files: .coverage/cobertura.xml 
          flags: unittests
          name: codecov-umbrella 
          fail_ci_if_error: true 
          verbose: true 
