name: Rust

on:
  push:
    branches:
      - "*"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run linter
      run: cargo clippy -- -D warnings

  unit-tests:
    if: github.ref != 'refs/heads/main'
    needs: [linter-check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose

  coverage-tests:
      if: github.ref == 'refs/heads/main'
      needs: [linter-check]
      runs-on: ubuntu-latest
      container:
        image: xd009642/tarpaulin:develop-nightly
        options: --security-opt seccomp=unconfined
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin \
          --engine llvm \
          --out xml \
          --output-dir .coverage
      - uses: codecov/codecov-action@v3
        with:
          files: .coverage/cobertura.xml 
          flags: unittests
          name: codecov-umbrella 
          fail_ci_if_error: true 
          verbose: true 
  
  package-publishing: 
    # if: github.ref == 'refs/heads/main'
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [coverage-tests]
    runs-on: ubuntu-latest